### ISSUE TITLE
Timing and other questions

### ISSUE THREAD

**Issue by seitzbg** [smxi/acxi#10] opened 2021-06-09 06:19 UTC
I am converting from FLAC to OPUS on a ~15TB library.
I ran acxi with -F 20 but it just sits there saying processing :)  How long should it take to start converting files?
Also will it copy all of the metadata from my FLAC files to the OPUS outputs by default?

Thanks!

**Comment by smxi** [comment] 2021-06-09 08:03
I've never tested it with as many as 20 forks, most I've done is about 10, but that tends to lead to odd behaviors I've found so I usually keep it to around 6 or 8, but that's with a ryzen 6 core, 12 threads. It depends I think on how many threads your  system actually can spare, keeping in mind it needs some to operate itself as well. I think I usually use about 1/2 the available threads on a big sync job. For me, overheating the cpu is a  bigger issue lol, since when most of the cores are running at near 100% for that long, heat buildup exposes a weak heatsink/cooler like I have.

If I were you with something that  big, I'd first just do  a  1 or 2 GB test with -F 20 and see if there are any issues because that's never been tested, you might have hit a Perl limit for all I know.

Conversion start should be quite fast, depends of course if spinning disk or ssd. 

Basically it's not going do any sync until it's made all the directories it will need, and those take almost no time to create, so usually you'll see something happen quite rapidly.

One reason I switched to Opus from Ogg, besides it being more efficient, was that all meta data, including images, transfers natively, so yes, it all transfers. There was no practical way to get image data to oggs without some really nasty hacks so I decided to switch to opus instead and just forget about ogg.

With all this said, 15 TB is going to challenge any system, since basically before acxi really starts the sync, it's going to collect all the data for the sync, well, for one file type at a time, but that means it will go through the library for each file type, but as noted, the directory build is fast because it's just directories, not files.

Since you are dealing with two areas I have never tested, one a 15 TB library, and 2 a 20 fork acxi process, I'd test the fork counts on a smaller bit of the collection first to make sure that's not the issue.

Let me know what you find, this would be good stuff to know.

**Comment by smxi** [comment] 2021-06-09 08:15
I double checked, fork would not be causing your slowdown because it is not invoked until the actual file sync action starts, so it is not running  during the first sync phases, directory creation, file copy, etc. So the issue is probably with File::Find hitting some serious slowdown, though I haven't seen a sign of that, but depending on your os/file system, that might be an issue. ext3 for example is slow in some huge bulk operations, it depends.

**Comment by smxi** [comment] 2021-06-09 17:33
While waiting for response, my current guess is either network file system like nfs, cifs/smb, or non unix file system.  Since Perl tends to be incredibly fast.

Just to test, using a reasonably slow cpu (athlon 2 core) on 2 TB of data stored on spinning disks, the initialization output is instant, since nothing has really happened except acxi checking everything before it starts, then I hit a  roughly 6-8 second pause as it starts hitting the various types it is going to process, per type, roughly. 

I tested this also with a network connection, and got similar speeds for that 2 TB roughly data. So you could be looking at something like 60-80 seconds for each global file type location and listing to happen. 

If you don't see instant output however for the Checking.... steps then there's something completely wrong that is not related to acxi.

But I won't speculate further, but I do see an area I can optimize acxi File;:/Find operation speeds I  believe if excludes are being used.

**Comment by smxi** [comment] 2021-06-09 18:46
I'm assuming that when you say "it just sits there saying processing", that means the pre-run tests all went fine, and it got to the actual processing steps, where I think the 15 TB of data is  simply so massive that it's going to take a long time to run through it. 

As noted, depends on os, file system, network or direct system, and a further unknown of  where it actually stopped. 

If it's just the size thing, it may simply take 2 or more minutes per file type to actually run through 15 GB, which would mean, just start it and walk away and do something else for the few hours it will take to do that job. If it never starts, that's  even more interesting, but would require more examination and data to figure out.

Since you're saying it just sits there processing, that suggests the directory creation part worked, and then it just took a long time per file type. Note that each file type will take roughly similar time to collect full path set for that type, and the last step there is when the input file type is hit, flac in this case, which is where Fork would activate.

```
Running acxi pretests.
Checking log/screen output level..................... Supported: 1
Checking DONT_USE_NLINK value........................ Supported: 1
Checking FORK value.................................. Supported: 8
Checking EXCLUDE data................................ Supported: 8
Checking source / destination directories............ Directories: exist
Checking input and output types...................... Valid: flac(in) opus(out)
Checking codecs...................................... Valid
Checking quality support for opus.................... Supported: 144 (opus)
Checking required tools paths........................ Available: 
 /usr/bin/opusenc
Pretests passed. Continuing.
Starting sync of /home/user/audio/flac
 to /home/user/audio/opus
Updating destination directories..................... None required
Processing gif data type............................. None found
Processing jpg data type............................. None to update
.....  and so on
```

**Comment by seitzbg** [comment] 2021-06-09 19:21
Sorry for my late reply and thank you for your lengthy replies :)  

yes it completes the pre-checks and outputs the find results then sits saying 'processing'.

The system has 384GB of ram, dual E5-2680V2 CPUs, and 12 disks in RaidZ-2 on ZFS.  It is running Fedora 33.

**Comment by seitzbg** [comment] 2021-06-09 19:28
```plex@pve2:/internal/music$ acxi -d /internal/music/Sorted-OPUS/ --input flac --output ogg -q 192 -s /internal/music/Sorted/ -S  --full -F 20
===========================================================================
Running acxi pretests.
Checking log/screen output level..................... Supported: 3
Checking DONT_USE_NLINK value........................ Supported: 1
Checking FORK value.................................. Supported: 20
---------------------------------------------------------------------------
Checking source / destination directories............ Directories: exist
---------------------------------------------------------------------------
Checking input and output types...................... Valid: flac(in) UNSET(out)
---------------------------------------------------------------------------
Checking codecs...................................... Valid
Checking required tools paths........................ Available:
Pretests passed. Continuing.
---------------------------------------------------------------------------
Creating auto.tag in /internal/music/Sorted...
/internal/music/Sorted
Checking for pre-existing auto.tag... none found. Proceeding.
```

**Comment by seitzbg** [comment] 2021-06-09 19:28
```Z/ZZ Ward/The Storm (2017) [16-Bit FLAC]/08 - She Ain't Me.flac
Z/ZZ Ward/The Storm (2017) [16-Bit FLAC]/09 - If U Stayed.flac
Z/ZZ Ward/The Storm (2017) [16-Bit FLAC]/10 - Hold On.flac
Z/ZZ Ward/The Storm (2017) [16-Bit FLAC]/11 - Ride.flac
Processing.
```

**Comment by seitzbg** [comment] 2021-06-09 21:30
Looks like it is reading each flac file per strace.

**Comment by smxi** [comment] 2021-06-09 22:43
hmmm, what start arguments are you using precisely. It should NOT be creating an auto.tag file, that's only applicable with -C,-S,-M. Let me double check that one. auto.tag should only be used if you completely understand how it's used, and it's NEVER used on directories of recordings, only inside them, unless you really understand how it works in  depth. And -C, -M, -S would NEVER be used in this context.

'that could be the source of your issue, all tagging stuff should never be used at the same time as syncing stuff, in fact, I will add an error handler that blocks that from happening.

It's going to look at every file, that's correct, but if you only got as far and no further, what's happening is you've triggered the auto.tag generation event somehow, and that's dutifully going through 15 TB of audio files looking for all the flacs it can find. 

That's probably your issue I'd  guess, that definitely needs protections added since that combinatation of events should never occur, tagging has zero to do with syncing, and  the two cannot operate at the same time.

**Comment by seitzbg** [comment] 2021-06-10 00:10
```acxi -d /internal/music/Sorted-OPUS/ --input flac --output ogg -q 192 -s /internal/music/Sorted/ -S  --full -F 20```

**Comment by smxi** [comment] 2021-06-10 00:24
Yes, -S is your problem, I'll fix the fact acxi allowed you to use that on a syncing operation. -S is --autotag-single and should not have been permitted to act with a sync action, I thought I had those filtered out already in an error handler but I must have missed something, thanks for finding  that little glitch. Actually there was another subtle glitch, not probably tripped in your case, but I tripped it when checking, failing to remove excludes correctly from File::Find lists via prune. I wouldn't use --full though for output, it's too verbaose and too difficult to see what acxi is actually doing as it  chugs through the data.

**Comment by seitzbg** [comment] 2021-06-10 00:25
Yeah I just want it to transfer tags from flac to opus, I don't know if I need any options for that?

**Comment by seitzbg** [comment] 2021-06-10 00:25
I do use embedded cover images on things but i'm also open for them going away and using cover.jpg in each dir.

**Comment by smxi** [comment] 2021-06-10 00:28
I like cover images, big fan, it took forever to get image embedding working, that's far harder to figure out than it should have been. 

-S has nothing to do with syncing however, it's only for flacs and only for tagging operations, never for syncing. That's why i never triipped that issue with no error handler stopping  that request before it could run, I never did it, but I did have error handling for most actions that are not compatible so that should have worked, must be a small oversight.

tags transfer automatically when you create the opus stuff, and the images also transfer automatically, nothing has to be done beyond syncing the directories. If you already have the opus files you unfortunately have to use -f for --force to force overwrite of the existing opus files.

**Comment by seitzbg** [comment] 2021-06-10 00:28
Also note it doesn't seem to interpret my output value of Opus in the summary!!  (Btw if you want to chat on irc or such, might be easier)

**Comment by seitzbg** [comment] 2021-06-10 00:32
Much better without -S.  Does it run faster if i don't have --full output? :)

**Comment by smxi** [comment] 2021-06-10 00:48
Yes, it runs faster. It takes time to print to your terminal, and it's impossible to read the progress with --full I find, I only use that for testing and debugging.

It would never have worked with -S, technically impossible because -S disables sync, basically what your system was being asked to do was create a MASSIVE auto.tag file with your entire collection's data in i t, that's why it was taking so long, it would have eventually generated a massive auto.tag file, I think, not sure. It's very tricky however enforcing -S being only run  on the directory you want to create an auto.tag file for, since I think it works on nested directories inside a primary release, so it's hard to know really what a user's intentions actually are.

I'm having some difficulty filtering out with error handling this scenario because acxi -s [source] -S is a valid command, the only sign there was the presence of the Destination directory, which -S ignores because it's irelevant.

**Comment by smxi** [comment] 2021-06-10 00:54
irc #smxi on either irc.oftc.net or on irc.libera.chat (I just setup that one) but I will only be around for a bit.

**Comment by smxi** [comment] 2021-06-10 00:56
ogg -q 192  is invalid, it should have exited with error, it doesn't use bitrate, it uses -1 - 10, fractions ok.

**Comment by seitzbg** [comment] 2021-06-10 00:58
```top - 00:58:25 up 27 days, 23:41,  4 users,  load average: 20.84, 17.52, 10.32
Tasks: 1497 total,  19 running, 1478 sleeping,   0 stopped,   0 zombie
%Cpu(s): 44.1 us,  1.0 sy,  0.0 ni, 54.4 id,  0.4 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 257692.9 total,  66923.5 free, 159208.2 used,  31561.2 buff/cache
MiB Swap:  65536.0 total,  65536.0 free,      0.0 used.  92856.1 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
17003 plex      20   0   10920   5352   3304 R 100.0   0.0   0:06.03 opusenc
17099 plex      20   0   11056   5244   3148 R 100.0   0.0   0:04.03 opusenc
17106 plex      20   0   11056   5188   3080 R 100.0   0.0   0:04.01 opusenc
16885 plex      20   0   10920   5276   3216 R 100.0   0.0   0:07.00 opusenc
16999 plex      20   0   10920   5356   3304 R 100.0   0.0   0:06.05 opusenc
17055 plex      20   0   11056   5284   3184 R 100.0   0.0   0:05.01 opusenc
17056 plex      20   0   11056   5304   3216 R 100.0   0.0   0:05.02 opusenc
17102 plex      20   0   11056   5400   3312 R 100.0   0.0   0:04.01 opusenc
17103 plex      20   0   11056   5396   3304 R 100.0   0.0   0:04.02 opusenc
17329 plex      20   0   11056   5184   3080 R  99.0   0.0   0:03.01 opusenc
17360 plex      20   0   11056   5308   3216 R  66.1   0.0   0:02.01 opusenc
17359 plex      20   0   11056   5376   3284 R  65.8   0.0   0:02.00 opusenc
17363 plex      20   0   11056   5376   3284 R  65.8   0.0   0:02.00 opusenc
17365 plex      20   0   10832   5096   3280 R  64.1   0.0   0:01.95 opusenc
17444 plex      20   0   10676   5100   3284 R  31.6   0.0   0:00.96 opusenc
17448 plex      20   0   10676   5104   3292 R  31.2   0.0   0:00.95 opusenc
17449 plex      20   0   11924   6336   3244 R  31.2   0.0   0:00.95 opusenc
17446 plex      20   0   10676   5100   3284 R  30.9   0.0   0:00.94 opusenc
 1765 plex      20   0  108632 102952   5108 S   1.3   0.0   1:40.90 perl
```

Looks good!

**Comment by smxi** [comment] 2021-06-10 00:58
Just to be  clear, auto.tag --autotag does NOT mean automatically tag files without doing anything, it means, use a  custom made auto.tag file to tag the files.

**Comment by smxi** [comment] 2021-06-10 16:28
I'm calling the allowing you to use -d, -i, -o, and -S  together a bug, I'm going to refactor that section to allow for much tighter cotnrols to protect against errors like that, I can see how it happened because the code was't really made with that type of protection in mind.

**Comment by smxi** [comment] 2021-06-12 02:39
I've refactored the basic option conflict error handling, now it seems to be much harder to use options that conflict in latest trunk version of acxi, so closing this issue.

**Closed by smxi** 2021-06-12 02:39 UTC
Labels: bug, fixed, interesting, question

**Comment by smxi** [comment] 2021-09-22 20:33
You might want to check out acxi 3.4.01, just got the last issues ironed out. New feature --dupes might be of use in a very large collection like you have, detects and prints out ffp duplicate flacs detected. Probably best to to run it on one primary directory at a time, not all of them, since if there's a lot of duplicates, output would get unwieldy. 
`acxi -s./ --dupes 2>&1 | tee dupe-file.txt`

Very  nifty feature. There's also --analyze/-Z which shows what is actually in each recording set of flacs. -v2 wraps to a key value pair per line, which gets very long for long datasets, but is easier to read.
